[build-system]
requires = ["setuptools >= 77.0.3", "requests == 2.32.5"]
build-backend = "setuptools.build_meta"

[project]
name = "openflag"
version = "0.0.1"
description = "SDK for a flag management server"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]